name: Publish

on:
  push: {tags: ['v*']}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: {python-version: 3.9}
      - run: pip install wheel pytest
      - run: pytest
      - run: python setup.py sdist bdist_wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with: {password: "${{ secrets.PYPI_PASSWORD }}"}
